# Generated by Django 5.0.7 on 2024-08-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactioRiskScore',
        ),
        migrations.AlterModelTable(
            name='transactioriskscore',
            table='TransactioRiskScore',
        ),
    ]
