# Generated by Django 5.0.7 on 2024-10-04 16:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_dates', models.JSONField(blank=True, null=True)),
                ('citizenships', models.JSONField(blank=True, null=True)),
                ('nationalities', models.JSONField(blank=True, null=True)),
                ('positions', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('download_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SanctionsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SDN', 'SDN'), ('NONSDN', 'NONSDN'), ('UK', 'UK'), ('EU', 'EU'), ('OFAC SDN', 'OFAC SDN'), ('OFAC Consolidated (non-SDN) List', 'OFAC Consolidated (non-SDN) List'), ('BIS Denied Persons List', 'BIS Denied Persons List'), ('UN Security Council Consolidated Sanctions', 'UN Security Council Consolidated Sanctions'), ('Office of Financial Sanctions Implementation', 'Office of Financial Sanctions Implementation'), ('EU Financial Sanctions Files (FSF)', 'EU Financial Sanctions Files (FSF)'), ('Politically Exposed Persons (PEP)', 'Politically Exposed Persons (PEP)'), ('Australian Department of Foreign Affairs and Trade (DFAT)', 'Australian Department of Foreign Affairs and Trade (DFAT)'), ('US FHFA Suspended Counterparty Program', 'US FHFA Suspended Counterparty Program'), ('US SAM Procurement Exclusions', 'US SAM Procurement Exclusions'), ('HUD Excluded Parties Listing', 'HUD Excluded Parties Listing'), ('Dual Use Items', 'Dual Use Items'), ('Canadian Special Economic Measures Act Sanctions', 'Canadian Special Economic Measures Act Sanctions'), ('Belgian Financial Sanctions', 'Belgian Financial Sanctions'), ('Swiss SECO Sanctions and Embargoes', 'Swiss SECO Sanctions and Embargoes'), ('Mexican Tax Code Article 69.B', 'Mexican Tax Code Article 69.B'), ('OIG List of Excluded Individuals and Entities', 'OIG List of Excluded Individuals and Entities'), ('Lithuanian FIU Sanctions', 'Lithuanian FIU Sanctions'), ('FinCEN 311 and 9714 Special Measures', 'FinCEN 311 and 9714 Special Measures')], max_length=100), size=None)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('person', 'person'), ('organization', 'organization'), ('vessel', 'vessel'), ('aircraft', 'aircraft')], max_length=20), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='VesselDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('call_sign', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('imo_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tonnage', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_tonnage', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=255)),
                ('match_type', models.CharField(max_length=255)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_formatted', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_link', models.URLField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('effective_date', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.JSONField(blank=True, null=True)),
                ('addresses', models.JSONField(blank=True, null=True)),
                ('identifications', models.JSONField(blank=True, null=True)),
                ('email_addresses', models.JSONField(blank=True, null=True)),
                ('phone_numbers', models.JSONField(blank=True, null=True)),
                ('websites', models.JSONField(blank=True, null=True)),
                ('crypto_wallets', models.JSONField(blank=True, null=True)),
                ('source_links', models.JSONField(blank=True, null=True)),
                ('programs', models.JSONField(blank=True, null=True)),
                ('additional_sanctions', models.JSONField(blank=True, null=True)),
                ('additional_information', models.JSONField(blank=True, null=True)),
                ('aircraft_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanctions.aircraftdetails')),
                ('person_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanctions.persondetails')),
                ('vessel_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanctions.vesseldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('match_count', models.IntegerField()),
                ('matches', models.ManyToManyField(to='sanctions.match')),
            ],
        ),
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('sources', models.ManyToManyField(to='sanctions.responsesource')),
                ('results', models.ManyToManyField(to='sanctions.result')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('crypto_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanctions.address')),
                ('identifications', models.ManyToManyField(related_name='cases', to='sanctions.identification')),
                ('sanctions_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='sanctions.sanctionsrequest')),
            ],
        ),
    ]
